gems:
- jekyll-paginate


url: ""
baseurl: ""

title: PBX Group Security - Candidate site
desc : PBX Group Security - Candidate site

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
  Home: ""
  About Me: "aboutme"
  Archive: "archive"
  
timezone: "Europe/London"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Babji, Chetty
creator-url: https://bchetty.com
